config/routes.rb
Rails.application.routes.draw do
  # Namespace para o backoffice do usuário
  namespace :users_backoffice do
    # Rotas específicas para o backoffice do usuário
    get 'welcome/index'
    # Defina corretamente a rota para confirmar o pedido dentro do namespace
    post 'confirm_order', to: 'orders#confirm', as: 'confirm_order'
  end

  # Namespace para páginas públicas do site
  namespace :site do
    get 'welcome/index'
  end

  # Configurações de autenticação com Devise
  devise_for :users

  # Rota de início do site
  get 'inicio', to: 'site/welcome#index'
  # Rota raiz do site
  root to: 'site/welcome#index'

  # Rotas para funcionalidades do carrinho
  get 'cart', to: 'cart#index', as: 'cart'
  post 'add_item_to_cart', to: 'cart#add_item_to_cart', as: 'add_item_to_cart'
  post 'finalize_order', to: 'cart#finalize_order', as: 'finalize_order'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  belongs_to :user
  belongs_to :processor, class_name: 'Product', optional: true
  belongs_to :motherboard, class_name: 'Product', optional: true
  belongs_to :ram, class_name: 'Product', optional: true
  belongs_to :video_card, class_name: 'Product', optional: true

  validates :processor, presence: true
  validates :motherboard, presence: true
  validates :ram, presence: true

  validate :validate_processor_compatibility
  validate :validate_ram_selection
  validate :validate_video_card_requirement

  private

  def validate_processor_compatibility
    return if processor.nil? || motherboard.nil?

    processor_brand = extract_specification(processor.specifications, 'Marca')
    supported_processors = extract_specification(motherboard.specifications, 'Processadores suportados').split(', ')

    unless supported_processors.include?(processor_brand)
      errors.add(:processor, "não é compatível com a placa-mãe selecionada")
    end
  end

  def validate_ram_selection
    return if ram.nil? || motherboard.nil?

    ram_slots = extract_specification(motherboard.specifications, 'Slots de memória').to_i
    max_ram_supported = extract_specification(motherboard.specifications, 'Memória suportada').to_i
    selected_ram_size = extract_specification(ram.specifications, 'Tamanho').to_i

    if selected_ram_size > max_ram_supported
      errors.add(:ram, "selecionada excede o total suportado pela placa-mãe")
    end
  end

  def validate_video_card_requirement
    return if motherboard.nil?

    video_integrado = extract_specification(motherboard.specifications, 'Vídeo integrado') == 'Sim'
    if !video_integrado && video_card.nil?
      errors.add(:video_card, "é necessária, pois a placa-mãe não possui vídeo integrado")
    end
  end

  # Helper method to extract a specification from a formatted string
  def extract_specification(specifications, key)
    specs = specifications.split(', ').map { |spec| spec.split(': ') }.to_h
    specs[key]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :specifications, presence: true
  validates :image_url, presence: true, allow_blank: true

  serialize :specifications, JSON

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'site'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_action :load_cart

  def index
    @items = session[:cart].map do |product_id, quantity|
      product = Product.find_by(id: product_id)
      { product: product, quantity: quantity } if product
    end.compact  # This will remove any nil entries if a product isn't found
  end

  def add_item_to_cart
    product_id = params[:product_id]
    quantity = params.fetch(:quantity, 1).to_i
  
    session[:cart] ||= {}  
    session[:cart][product_id] = (session[:cart][product_id] || 0) + quantity
  
    @current_step = params[:current_step]
    @next_step = params[:next_step]
  
    respond_to do |format|
      #format.html { redirect_to root_path, notice: 'Produto adicionado ao carrinho com sucesso!' }
      #format.json { render notify: 'Produto adicionado ao carrinho com sucesso!'}
      format.js
    end
  end
  
  
  
  private

  def load_cart
    session[:cart] ||= {}
  end

end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < ApplicationController
  before_action :set_order

  def index
    @processors = Product.where(category_id: 1)
    @motherboards = Product.where(category_id: 2)
    @ram_cards = Product.where(category_id: 3)
    @video_cards = Product.where(category_id: 4)
  end

  private

  def set_order
    @order = current_order
  end

  def current_order
    # Se o usuário está logado, buscar ou criar um pedido com status 'open'
    if user_signed_in?
      order = Order.find_or_create_by(user_id: current_user.id, status: 'open')
    else
      # Se não está logado, pode-se escolher criar um pedido temporário na sessão
      order = Order.find_by(id: session[:order_id], status: 'open')
      unless order
        order = Order.new(status: 'open')
        session[:order] = order
      end
    end
    order
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
    
end

app/controllers/users_backoffice/orders_controller.rb
module UsersBackoffice
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def confirm
      @order = current_user.orders.build
      build_order_from_session

      if @order.save
        # Limpa a sessão do carrinho após salvar o pedido com sucesso
        session[:cart].clear
        flash[:notice] = 'Pedido confirmado com sucesso!'
        # Permanece na página do carrinho
        redirect_back(fallback_location: users_backoffice_welcome_index_path)
        puts "OK"
      else
        # Em caso de falha, redireciona para o menu inicial com uma mensagem de erro
        flash[:alert] = 'Não foi possível completar seu pedido: ' + @order.errors.full_messages.to_sentence
        redirect_to root_path
        puts "FAIL"
      end
    end
  
    private

    def build_order_from_session
      # Supondo que você tem ids de produtos e quantidades em session[:cart]
      session[:cart].each do |product_id, quantity|
        product = Product.find(product_id)
        # Adiciona produto ao pedido
        @order.order_items.build(product: product, quantity: quantity)
      end
    end
    
  end
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  before_action :load_cart_items

  def index
    load_cart_items
  end

  private

  def load_cart_items
    if session[:cart].present?
      cart_items_ids = session[:cart].keys
      @cart_items = Product.find(cart_items_ids)
    else
      @cart_items = []
    end
  end
end
  

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/orders_helper.rb
module UsersBackoffice::OrdersHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/cart/add_item_to_cart.js.erb
<% if @next_step && @current_step %>

  $('#<%= @current_step %>').hide();
  $('#<%= @next_step %>').show();

  updateProgressBar('<%= @next_step %>');

<% else %>

  alert('Produto adicionado ao carrinho com sucesso!');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <div class="left-menu">
      <ul class="horizontal-list" >
        <li>
          <%= image_tag "folha.png", height: "40", width: "40", style: "margin-right: 10px;" %>
          <a href="#", style="align-items: center;">EcoTech</a>
        </li>
        <li>
          <a href="#">Service</a>
        </li>
        <li>
          <a href="#">About</a>
        </li>
        <li>
          <a href="#">Contact</a>
        </li>
        <li>
          <a href="#">FAQ</a>
        </li>
      </ul>
    </div>
    <div class="right-menu">
      <ul class="horizontal-list" >
        <li>
          <button class="btn-plain">
            <%= image_tag "carrinho3.png", height: "50", width: "50"%>
          </button>
        </li>
        <li class="dropdown">
          <button   class="btn-plain">
            <%= image_tag "profile.png", height: "50", width: "50" %>
          </button>
          <div class="dropdown-content">
            <a href="#">Editar</a>
            <a href="#">Sair</a>
          </div>
        </li>
      </ul>
    </div>
  </header>
  <%= yield %>
</body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/site/welcome/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TenderQuestions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag     'site' %>

  </head>
  <body>
    <div class="container-fluid">
      <div class="row justify-content-center" style="background-color: white">
        <div class="col-11 col-sm-9 col-md-7 col-lg-6 col-xl-5 text-center p-0 mt-3 mb-2">
          <div class="card px-0 pt-4 pb-0 mt-3 mb-3">
          <% if flash[:notice] %>
            <div id="flash_notice" class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
            <h2 id="heading">Barra de Progresso para seu PC</h2>
            <p>Adicione o item ao carrinho e prossiga</p>
            <form id="msform">
              <ul id="progressbar">
                <li class="active" id="step1_progress">
                  <%= image_tag "processador.jpg", alt: "Processor", style: "height: 50px; width: 50px; margin: 0 auto; display: block;" %>
                  <b>Processador</b>
                </li>
                <li id="step2_progress">
                  <%= image_tag "mother.jpg", alt: "Mother Board", style: "height: 50px; width: 50px; margin: 0 auto; display: block;" %>
                  <b>Placa Mãe</b>
                </li>
                <li id="step3_progress">
                  <%= image_tag "ram.png", alt: "Ram", style: "height: 50px; width: 50px; margin: 0 auto; display: block;" %>
                  <b>Memória RAM</b>
                </li>
                <li id="step4_progress">
                  <%= image_tag "video.png", alt: "Video", style: "height: 50px; width: 50px; margin: 0 auto; display: block;" %>
                  <b>Placa de Vídeo</b>
                </li>
              </ul>
              <div class="progress">
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <br>

              <fieldset id="step1" class="form-card">
                <div class="row justify-content-center">
                  <div class="col-10">
                    <div class="row">
                      <div class="col-12 text-center">
                        <h2 class="fs-title">Escolha seu Processador</h2>
                        <h2 class="steps">Step 1 - 4</h2>
                      </div>
                    </div>
                    <div class="row justify-content-center">
                      <% @processors.each_with_index do |processor, index| %>
                        <div class="col-md-6 col-lg-4 mb-4">
                          <div class="card text-center" style="width: 10rem;">
                            <img src="<%= processor.image_url %>" class="card-img-top mx-auto" alt="<%= processor.name %>" style="height: 100px; width: 100px;">
                            <div class="card-body">
                              <h5 class="card-title"><%= processor.name %></h5>
                              <p class="card-text"><%= processor.specifications %></p>
                              <%= link_to "Adicionar", add_item_to_cart_path(product_id: processor.id), method: :post, remote: true, class: "btn btn-primary add-to-cart", data: {next_step: "step2", current_step: "step1"} %>
                            </div>
                          </div>
                        </div>
                        <% if index % 2 == 1 %>
                          </div><div class="row justify-content-center">
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </fieldset>

              <fieldset id="step2" class="form-card" style="display:none;">
                <div class="row justify-content-center">
                  <div class="col-10">
                    <div class="row">
                      <div class="col-12 text-center">
                        <h2 class="fs-title">Escolha sua Placa Mãe</h2>
                        <h2 class="steps">Step 2 - 4</h2>
                      </div>
                    </div>
                    <div class="row justify-content-center">
                      <% @motherboards.each_with_index do |motherboard, index| %>
                        <div class="col-md-6 mb-4">
                          <div class="card text-center" style="width: 18rem; margin: 15px;">
                            <img src="<%= motherboard.image_url %>" class="card-img-top mx-auto" alt="<%= motherboard.name %>" style="height: 100px; width: 100px;">
                            <div class="card-body">
                              <h5 class="card-title"><%= motherboard.name %></h5>
                              <p class="card-text"><%= motherboard.specifications %></p>
                              <%#= link_to "Adicionar", add_item_to_cart_path(product_id: processor.id), method: :post, remote: true, class: "btn btn-primary add-to-cart", data: {next_step: "step2", current_step: "step1"} %>
                              <%= link_to "Adicionar", add_item_to_cart_path(product_id: motherboard.id), method: :post, remote: true, class: "btn btn-primary add-to-cart", data: {next_step: "step3", current_step: "step2"} %>
                            </div>
                          </div>
                        </div>
                        <% if (index + 1) % 2 == 0 && (index + 1) != @motherboards.count %>
                          </div><div class="row justify-content-center">
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </fieldset>

              <fieldset id = "step3" class="form-card" style="display:none;">
                <div class="row justify-content-center">
                  <div class="col-10">
                    <div class="row">
                      <div class="col-12 text-center">
                        <h2 class="fs-title">Escolha sua Memória RAM</h2>
                        <h2 class="steps">Step 3 - 4</h2>
                      </div>
                    </div>
                    <div class="row justify-content-center">
                      <% @ram_cards.each_with_index do |ram_card, index| %>
                        <div class="col-md-6 col-lg-4 mb-4">
                          <div class="card text-center" style="width: 10rem;">
                            <img src="<%= ram_card.image_url %>"  class="card-img-top mx-auto" alt="<%= ram_card.name %>" style="height: 100px; width: 100px;">
                            <div class="card-body">
                              <h5 class="card-title"><%= ram_card.name %></h5>
                              <p class="card-text"><%= ram_card.specifications %></p>
                              <%#= link_to "Adicionar", add_item_to_cart_path(product_id: processor.id), method: :post, remote: true, class: "btn btn-primary add-to-cart", data: {next_step: "step2", current_step: "step1"} %>
                              <%= link_to "Adicionar", add_item_to_cart_path(product_id: ram_card.id), method: :post, remote: true, class: "btn btn-primary add-to-cart", data: {next_step: "step4", current_step: "step3"} %>
                            </div>
                          </div>
                        </div>
                        <% if index % 2 == 1 %>
                          </div><div class="row justify-content-center">
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </fieldset>

              <fieldset id="step4" class="form-card" style="display:none;">
                <div class="row justify-content-center">
                  <div class="col-10">
                    <div class="row">
                      <div class="col-12 text-center">
                        <h2 class="fs-title">Escolha sua Placa de Vídeo</h2>
                        <h2 class="steps">Step 4 - 4</h2>
                      </div>
                    </div>
                    <div class="row justify-content-center">
                      <% @video_cards.each_with_index do |video_card, index| %>
                        <div class="col-md-6 mb-4">
                          <div class="card text-center" style="width: 18rem; margin: 15px;">
                            <img src="<%= video_card.image_url %>" class="card-img-top mx-auto" alt="<%= video_card.name %>" style="height: 100px; width: 100px;">
                            <div class="card-body">
                              <h5 class="card-title"><%= video_card.name %></h5>
                              <p class="card-text"><%= video_card.specifications %></p>
                              <%= link_to "Adicionar", add_item_to_cart_path(product_id: video_card.id), method: :post, remote: true, class: "btn btn-primary" %>
                            </div>
                          </div>
                        </div>
                        <% if (index + 1) % 2 == 0 && (index + 1) != @video_cards.count %>
                          </div><div class="row justify-content-center">
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <%= link_to "Finalizar", users_backoffice_welcome_index_path, class:"btn action-button"%>
              </fieldset>
              
            </form>
          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag  'site' %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/index.html.erb
<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
        </div>

        <% @cart_items.each do |item| %>
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                  <img src="<%= item.image_url %>" class="img-fluid rounded-3" alt="<%= item.name %>">
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2"><%= item.name %></p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                  <button class="btn btn-link px-2" onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>

                  <button class="btn btn-link px-2" onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                  <h5 class="mb-0">Preço</h5>
                </div>
                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                  <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
          
        <div class="card mb-4">
          <div class="card-body p-4 d-flex flex-row">
            <div class="form-outline flex-fill">
              <input type="text" id="form1" class="form-control form-control-lg" />
              <label class="form-label" for="form1">Discound code</label>
            </div>
            <button class="btn btn-outline-warning btn-lg ms-3">Apply</button>
          </div>
        </div>

        <%= form_with url: users_backoffice_confirm_order_path, local: true do |form| %>
          <%= form.submit "Confirmar Pedido", class: "btn btn-warning btn-block btn-lg" %>
        <% end %>

      </div>
    </div>
  </div>
</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
</body>